# Generated by Django 4.2.5 on 2023-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('image', models.ImageField(upload_to='blog_image/', verbose_name='фото')),
                ('descriptions', models.TextField(verbose_name='описание')),
                ('make_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': ('Новость',),
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
