# Generated by Django 4.2.5 on 2023-09-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook_url',
            field=models.URLField(default=1, verbose_name='Ссылка на Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_url',
            field=models.URLField(default=1, verbose_name='Ссылка на Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='linkeldin_url',
            field=models.URLField(default=1, verbose_name='Ссылка на Linkeldin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
    ]
