# Generated by Django 4.2.5 on 2023-09-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name': 'Учеьная программа',
                'verbose_name_plural': 'Учеьная программа',
            },
        ),
    ]
