# Generated by Django 4.2.5 on 2023-10-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_teach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Teach',
        ),
    ]
