# Generated by Django 4.2.5 on 2023-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logon',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип сайта'),
            preserve_default=False,
        ),
    ]
