# Generated by Django 4.2.5 on 2023-10-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_settings_descriptions_settings_logon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='logon',
            new_name='logo',
        ),
    ]
