# Generated by Django 4.2.5 on 2023-10-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_settings_options_rename_logon_settings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя пользоветеля')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('message', models.TextField(verbose_name='сообщении')),
            ],
            options={
                'verbose_name': 'Обратная связ',
                'verbose_name_plural': 'обратные связи',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройка'},
        ),
    ]
